services:

  postgres-db:
    image: postgres:15.1
    container_name: postgres-container
    ports:
      - "15432:5432" # Expose db port 5432 on port 15432 (default postgres port: 5432) - Change if in use
    environment:
      # Values defined in .env
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"

  clickhouse-db:
    image: clickhouse/clickhouse-server:22.8
    container_name: clickhouse-container
    ports:
      - "18123:8123" # Expose db port 8123 on port 18123 (default clickhouse HTTP port: 8123) - Change if in use
      - "19000:9000" # Expose db port 9000 on port 19000 (default clickhouse TCP port: 9000) - Change if in use
    environment:
      # Values defined in .env
      CLICKHOUSE_USER: "${CHUSER}"
      CLICKHOUSE_PASSWORD: "${CHPASSWORD}"
      CLICKHOUSE_DB: "${CHDATABASE}"
