"""postgres: Initialize imdb tables

Revision ID: 5573c1201da3
Revises: a7c0de3cdadd
Create Date: 2023-06-04 12:38:09.958297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5573c1201da3'
down_revision = 'a7c0de3cdadd'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_postgresql() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'name_basics',
        sa.Column('nconst', sa.String(length=256), nullable=False),
        sa.Column('primary_name', sa.String(length=256), nullable=False),
        sa.Column('birth_year', sa.String(length=256), nullable=False),
        sa.Column('death_year', sa.String(length=256), nullable=True),
        sa.Column('primary_profession', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.Column('known_for_titles', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.PrimaryKeyConstraint('nconst')
    )
    op.create_table(
        'title_akas',
        sa.Column('title_id', sa.String(length=256), nullable=False),
        sa.Column('ordering', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=256), nullable=False),
        sa.Column('region', sa.String(length=256), nullable=False),
        sa.Column('language', sa.String(length=256), nullable=False),
        sa.Column('types', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.Column('attributes', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.Column('is_original_title', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('title_id')
    )
    op.create_table(
        'title_basics',
        sa.Column('tconst', sa.String(length=256), nullable=False),
        sa.Column('title_type', sa.String(length=256), nullable=False),
        sa.Column('primary_title', sa.String(length=256), nullable=False),
        sa.Column('original_title', sa.String(length=256), nullable=False),
        sa.Column('is_adult', sa.Boolean(), nullable=False),
        sa.Column('start_year', sa.Integer(), nullable=False),
        sa.Column('end_year', sa.Integer(), nullable=True),
        sa.Column('runtime_minutes', sa.Integer(), nullable=False),
        sa.Column('genres', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table(
        'title_crew',
        sa.Column('tconst', sa.String(length=256), nullable=False),
        sa.Column('directors', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.Column('writers', sa.ARRAY(sa.String(length=256)), nullable=False),
        sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table(
        'title_episode',
        sa.Column('tconst', sa.String(length=256), nullable=False),
        sa.Column('parent_tconst', sa.String(length=256), nullable=False),
        sa.Column('season_number', sa.Integer(), nullable=False),
        sa.Column('episode_number', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table(
        'title_principals',
        sa.Column('tconst', sa.String(length=256), nullable=False),
        sa.Column('ordering', sa.Integer(), nullable=False),
        sa.Column('nconst', sa.String(length=256), nullable=False),
        sa.Column('category', sa.String(length=256), nullable=False),
        sa.Column('job', sa.String(length=256), nullable=True),
        sa.Column('characters', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table(
        'title_ratings',
        sa.Column('tconst', sa.String(length=256), nullable=False),
        sa.Column('average_rating', sa.Float(), nullable=False),
        sa.Column('num_votes', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tconst')
    )
    # ### end Alembic commands ###


def downgrade_postgresql() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_ratings')
    op.drop_table('title_principals')
    op.drop_table('title_episode')
    op.drop_table('title_crew')
    op.drop_table('title_basics')
    op.drop_table('title_akas')
    op.drop_table('name_basics')
    # ### end Alembic commands ###


def upgrade_clickhouse() -> None:
    pass


def downgrade_clickhouse() -> None:
    pass
