"""clickhouse: Initialize imdb tables

Revision ID: b1fe2784ca6f
Revises: 5573c1201da3
Create Date: 2023-06-04 14:42:18.161394

"""
from alembic import op
import sqlalchemy as sa
import clickhouse_sqlalchemy as ch_sa
from clickhouse_sqlalchemy.engines import MergeTree


# revision identifiers, used by Alembic.
revision = 'b1fe2784ca6f'
down_revision = '5573c1201da3'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_postgresql() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_postgresql() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_clickhouse() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'name_basics',
        sa.Column('nconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('primary_name', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('birth_year', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('death_year', ch_sa.types.common.String(length=256), nullable=True),
        sa.Column('primary_profession', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.Column('known_for_titles', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.PrimaryKeyConstraint('nconst'),
        MergeTree(primary_key='nconst')
    )
    op.create_table(
        'title_akas',
        sa.Column('title_id', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('ordering', ch_sa.types.common.Int(), nullable=False),
        sa.Column('title', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('region', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('language', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('types', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.Column('attributes', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.Column('is_original_title', ch_sa.types.common.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('title_id'),
        MergeTree(primary_key='title_id')
    )
    op.create_table(
        'title_basics',
        sa.Column('tconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('title_type', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('primary_title', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('original_title', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('is_adult', ch_sa.types.common.Boolean(), nullable=False),
        sa.Column('start_year', ch_sa.types.common.Int(), nullable=False),
        sa.Column('end_year', ch_sa.types.common.Int(), nullable=True),
        sa.Column('runtime_minutes', ch_sa.types.common.Int(), nullable=False),
        sa.Column('genres', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.PrimaryKeyConstraint('tconst'),
        MergeTree(primary_key='tconst')
    )
    op.create_table(
        'title_crew',
        sa.Column('tconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('directors', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.Column('writers', ch_sa.types.common.Array(
            ch_sa.types.common.String(length=256)
        ), nullable=False),
        sa.PrimaryKeyConstraint('tconst'),
        MergeTree(primary_key='tconst')
    )
    op.create_table(
        'title_episode',
        sa.Column('tconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('parent_tconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('season_number', ch_sa.types.common.Int(), nullable=False),
        sa.Column('episode_number', ch_sa.types.common.Int(), nullable=False),
        sa.PrimaryKeyConstraint('tconst'),
        MergeTree(primary_key='tconst')
    )
    op.create_table(
        'title_principals',
        sa.Column('tconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('ordering', ch_sa.types.common.Int(), nullable=False),
        sa.Column('nconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('category', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('job', ch_sa.types.common.String(length=256), nullable=True),
        sa.Column('characters', ch_sa.types.common.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('tconst'),
        MergeTree(primary_key='tconst')
    )
    op.create_table(
        'title_ratings',
        sa.Column('tconst', ch_sa.types.common.String(length=256), nullable=False),
        sa.Column('average_rating', ch_sa.types.common.Float(), nullable=False),
        sa.Column('num_votes', ch_sa.types.common.Int(), nullable=False),
        sa.PrimaryKeyConstraint('tconst'),
        MergeTree(primary_key='tconst')
    )
    # ### end Alembic commands ###


def downgrade_clickhouse() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_ratings')
    op.drop_table('title_principals')
    op.drop_table('title_episode')
    op.drop_table('title_crew')
    op.drop_table('title_basics')
    op.drop_table('title_akas')
    op.drop_table('name_basics')
    # ### end Alembic commands ###
